# Generated by Django 5.2.6 on 2025-09-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_cents',
            new_name='price',
        ),
    ]
