# Generated by Django 5.2.6 on 2025-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider_name', 'appointment_time')},
        ),
    ]
