# Generated by Django 5.2.6 on 2025-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_price_alter_appointment_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
    ]
